image:
  file: Dockerfile

# Commands to start on workspace startup
tasks:
  - init: npm ci

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - https://github.com/freeCodeCamp/courses-vscode-extension/releases/download/v3.0.0/freecodecamp-courses-3.0.0.vsix
